#!/usr/bin/python
import os
import sys

sys.path.insert(0, os.path.dirname(__file__) or '.')
if os.path.exists(os.path.join("/Users/admin/code/pythonws/bin/python2.7")):
    PY_DIR = os.path.join("/Users/admin/code/pythonws/bin/python2.7")
else:
    PY_DIR = os.path.join("/Users/admin/code/pythonws/bin/python")


virtenv = PY_DIR

PY_CACHE = os.path.join(virtenv, 'lib', '2.7', 'site-packages')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from myflaskapp import app as application

